### ISSUE TITLE
Can you add an option to automatically add 10% of the views generated into likes, shares etc... ?

### ISSUE THREAD

**Issue by Zeffut** [terafear/TikTok-Automation-Bot#1]

**Comment by terafear** [comment]
I don't run the zefoy site so I cant do anything like because of the way the site works. Sorry I can't help with that. What I do is run the script in 3 terminals one for views one for shares and one for favorites. When zefoy updates the likes feature the script will show it online.

**Comment by terafear** [comment]
I don't run the zefoy site so I cant do anything like because of the way the site works. Sorry I can't help with that. What I do is run the script in 3 terminals one for views one for shares and one for favorites. When zefoy updates the likes feature the script will show it online.
